/**
 * C4G Content Generators
 *
 * Shared content generation for workspace files.
 * Used by both provisioner.js and c4g-update-containers.js.
 */

function generateIdentityMd(opName, brand, tone) {
  return [
    '# IDENTITY.md - Who Am I?',
    '',
    `- **Name:** ${opName}`,
    `- **Creature:** AI marketing operator`,
    `- **Vibe:** ${tone}, helpful, proactive`,
    `- **Emoji:** 🚀`,
    '',
    `I am ${opName}, the dedicated marketing operator for ${brand.name}.`,
    `I help with digital marketing tasks: content creation, campaign management, analytics, and more.`,
  ].join('\n');
}

function generateUserMd(brand, tone) {
  return [
    '# USER.md - About Your Human',
    '',
    `- **Brand:** ${brand.name}`,
    `- **Industry:** ${brand.industry}`,
    `- **Description:** ${brand.description || 'N/A'}`,
    `- **Website:** ${brand.website || 'N/A'}`,
    `- **Preferred tone:** ${tone}`,
    '',
    '## Context',
    '',
    `This user runs ${brand.name} in the ${brand.industry} space.`,
    `They use Claw4Growth to automate their digital marketing.`,
    `Always communicate in a ${tone} tone.`,
  ].join('\n');
}

function generateBootstrapMd(opName, brand, tone) {
  return [
    `# Welcome!`,
    ``,
    `You are **${opName}**, the marketing operator for **${brand.name}**.`,
    `Your tone is **${tone}**. You help with digital marketing tasks.`,
    ``,
    `## First Message`,
    ``,
    `Introduce yourself briefly. Something like:`,
    ``,
    `> "Hey! I'm ${opName}, your marketing operator for ${brand.name}. 🚀`,
    `> I can help with content creation, campaign management, analytics, and more.`,
    `> What would you like to work on?"`,
    ``,
    `Also mention that they can manage their integrations and subscription at:`,
    `**https://claw4growth.com/dashboard/**`,
    ``,
    `## After the first conversation`,
    ``,
    `Delete this file — you don't need it anymore.`,
  ].join('\n');
}

function generateBrandMemory(brand, tone) {
  return [
    `# Brand: ${brand.name}`,
    `## Industry: ${brand.industry}`,
    `## Description: ${brand.description || 'N/A'}`,
    `## Tone: ${tone}`,
    `## Website: ${brand.website || 'N/A'}`,
  ].join('\n');
}

function generateModelsMd() {
  return [
    '# Available AI Models',
    '',
    'You are currently using **GPT-4o Mini** — fast and cost-effective for most tasks.',
    '',
    '## When to suggest a model upgrade',
    '',
    'For particularly complex tasks, you can suggest using a more capable model.',
    'ONLY suggest this when the task genuinely requires it:',
    '',
    '- **Deep data analysis** with large datasets or complex reasoning',
    '- **Long-form strategy documents** requiring nuanced business insight',
    '- **Complex multi-step campaigns** with many variables',
    '- **Code generation** for advanced automations or integrations',
    '',
    '## How to suggest',
    '',
    'When you think a stronger model would help, ask the user:',
    '',
    '> "This task is quite complex. I can handle it with my current model (GPT-4o Mini),',
    '> but for best results I\'d suggest switching to a more powerful model for this specific task.',
    '> It will cost a bit more from your monthly budget. Would you like to upgrade for this task?"',
    '',
    '## Available models (by cost)',
    '',
    '| Model | Best for | Relative cost |',
    '|-------|----------|---------------|',
    '| GPT-4o Mini | General tasks, quick responses | $ (default) |',
    '| Gemini 2.0 Flash | Fast tasks, similar to Mini | $ |',
    '| Claude Haiku 4 | Quick analytical tasks | $$ |',
    '| GPT-4o | Complex reasoning, analysis | $$$ |',
    '| Gemini 2.5 Pro | Deep analysis, long context | $$$ |',
    '| Claude Sonnet 4 | Best quality writing & reasoning | $$$$ |',
    '',
    '## Important',
    '',
    '- NEVER switch model without asking the user first',
    '- NEVER mention model names proactively — only when the user asks or the task warrants it',
    '- After the complex task is done, switch back to GPT-4o Mini',
    '- The user has a monthly budget cap — be mindful of costs',
  ].join('\n');
}

function generateComposioMd() {
  return [
    '# App Integrations',
    '',
    'You have access to connected apps via TWO bridge scripts.',
    'The user connected these apps through the Claw4Growth dashboard.',
    '',
    '## IMPORTANT: Two Bridges',
    '',
    '- **Google apps** (Google Ads) → use `google-bridge.js`',
    '- **All other apps** (Gmail, Calendar, Drive, Meta, LinkedIn, etc.) → use `composio-bridge.js`',
    '',
    '---',
    '',
    '## Google Bridge (Google Ads)',
    '',
    '### List connected Google apps',
    '```bash',
    'node /opt/composio-bridge/google-bridge.js list-apps $USER_ID',
    '```',
    '',
    '### List available Google tools',
    '```bash',
    'node /opt/composio-bridge/google-bridge.js list-tools $USER_ID googleads',
    '```',
    '',
    '### Execute a Google tool',
    '```bash',
    `node /opt/composio-bridge/google-bridge.js execute $USER_ID TOOL_SLUG '{"param":"value"}'`,
    '```',
    '',
    '### Google Ads Tools',
    '- `GOOGLEADS_GET_ACCOUNT_INFO` — no args. Account name, currency, timezone',
    '- `GOOGLEADS_LIST_CAMPAIGNS` — no args (optional: `{"limit":10}`). All campaigns with metrics',
    '- `GOOGLEADS_GET_CAMPAIGN` — args: `{"campaign_id":"123"}`. Single campaign details',
    '- `GOOGLEADS_LIST_AD_GROUPS` — args: `{"campaign_id":"123"}`. Ad groups in a campaign',
    '- `GOOGLEADS_LIST_ADS` — args: `{"ad_group_id":"456"}`. Ads in an ad group',
    '- `GOOGLEADS_GET_METRICS` — args: `{"campaign_id":"123","start_date":"2025-01-01","end_date":"2025-01-31"}`. Daily metrics',
    '- `GOOGLEADS_GET_BUDGETS` — no args. All campaign budgets',
    '- `GOOGLEADS_LIST_KEYWORDS` — args: `{"ad_group_id":"456"}`. Keywords in an ad group',
    '',
    '**Google Ads workflow:** Start with `GOOGLEADS_GET_ACCOUNT_INFO` to verify the connection, then `GOOGLEADS_LIST_CAMPAIGNS` to see campaigns.',
    '',
    '---',
    '',
    '## Composio Bridge (Everything Else)',
    '',
    '### List connected apps',
    '```bash',
    'node /opt/composio-bridge/composio-bridge.js list-apps $USER_ID',
    '```',
    '',
    '### List available tools for an app',
    '```bash',
    'node /opt/composio-bridge/composio-bridge.js list-tools $USER_ID gmail',
    '```',
    '',
    '### Execute a tool',
    '```bash',
    `node /opt/composio-bridge/composio-bridge.js execute $USER_ID TOOL_SLUG '{"param":"value"}'`,
    '```',
    '',
    '## Composio Tools',
    '',
    '### Gmail',
    '- `GMAIL_GET_PROFILE` — no args needed. Returns email address and stats',
    '- `GMAIL_FETCH_EMAILS` — args: `{"max_results":5}`',
    '- `GMAIL_SEND_EMAIL` — args: `{"to":"email","subject":"...","body":"..."}`',
    '- `GMAIL_CREATE_EMAIL_DRAFT` — args: `{"to":"email","subject":"...","body":"..."}`',
    '- `GMAIL_LIST_THREADS` — list email threads',
    '- `GMAIL_FETCH_MESSAGE_BY_THREAD_ID` — args: `{"thread_id":"..."}`',
    '- `GMAIL_REPLY_TO_THREAD` — reply to an existing thread',
    '- `GMAIL_LIST_LABELS` — list all labels/folders',
    '- `GMAIL_CREATE_LABEL` — create a new label',
    '- `GMAIL_GET_ATTACHMENT` — get email attachment',
    '',
    '### Google Calendar',
    '- `GOOGLECALENDAR_EVENTS_LIST` — args: `{"calendarId":"primary"}`',
    '- `GOOGLECALENDAR_CREATE_EVENT` — args: `{"summary":"...","start":{"dateTime":"..."},"end":{"dateTime":"..."}}`',
    '- `GOOGLECALENDAR_UPDATE_EVENT` — update an existing event',
    '- `GOOGLECALENDAR_DELETE_EVENT` — delete an event',
    '- `GOOGLECALENDAR_QUICK_ADD` — create event from natural language text',
    '- `GOOGLECALENDAR_GET_CALENDAR` — get calendar info',
    '',
    '### Google Drive',
    '- `GOOGLEDRIVE_FIND_FILE` — args: `{"query":"filename","page_size":10}` — search files',
    '- `GOOGLEDRIVE_LIST_FILES` — list files in Drive',
    '- `GOOGLEDRIVE_CREATE_FOLDER` — create a new folder',
    '- `GOOGLEDRIVE_CREATE_FILE_FROM_TEXT` — create a file from text content',
    '- `GOOGLEDRIVE_COPY_FILE` — copy an existing file',
    '- `GOOGLEDRIVE_UPLOAD_FILE` — upload a file',
    '',
    '### Google Docs',
    '- `GOOGLEDOCS_CREATE_DOCUMENT` — create a new document',
    '- `GOOGLEDOCS_GET_DOCUMENT_BY_ID` — args: `{"document_id":"..."}` — get document content',
    '',
    '### Google Sheets',
    '- `GOOGLESHEETS_CREATE_GOOGLE_SHEET1` — args: `{"title":"Sheet Name"}` — create new spreadsheet',
    '- `GOOGLESHEETS_GET_SPREADSHEET_INFO` — args: `{"spreadsheet_id":"..."}` — get spreadsheet metadata',
    '- `GOOGLESHEETS_BATCH_GET` — args: `{"spreadsheet_id":"...","ranges":["Sheet1!A1:Z100"]}` — read data',
    '- `GOOGLESHEETS_BATCH_UPDATE` — write data to cells',
    '- `GOOGLESHEETS_LOOKUP_SPREADSHEET_ROW` — search for a row',
    '- `GOOGLESHEETS_SHEET_FROM_JSON` — create a sheet from JSON data',
    '- `GOOGLESHEETS_CLEAR_VALUES` — clear cell values',
    '',
    '### Google Analytics',
    '- `GOOGLE_ANALYTICS_LIST_ACCOUNTS` — no args needed. List all GA4 accounts',
    '',
    '### Facebook',
    '- `FACEBOOK_GET_USER_PAGES` — no args needed. Lists pages the user manages',
    '- `FACEBOOK_CREATE_PAGE_POST` — args: `{"page_id":"...","message":"..."}`',
    '- `FACEBOOK_GET_PAGE_INSIGHTS` — args: `{"page_id":"..."}`',
    '',
    '### Instagram',
    '- `INSTAGRAM_GET_USER_INFO` — no args needed. Returns profile info, followers, media count',
    '- `INSTAGRAM_GET_MEDIA` — get recent posts',
    '- `INSTAGRAM_CREATE_MEDIA` — create a post',
    '',
    '### Meta Ads',
    '- `METAADS_GET_AD_ACCOUNTS` — no args needed. Returns all ad accounts the user has access to',
    '- `METAADS_GET_INSIGHTS` — args: `{"ad_account_id":"act_123456","date_preset":"last_30d"}` — campaign performance',
    '- `METAADS_READ_ADSETS` — args: `{"ad_account_id":"act_123456"}` — list ad sets',
    '- `METAADS_CREATE_CAMPAIGN` — args: `{"ad_account_id":"act_123456","name":"...","objective":"OUTCOME_TRAFFIC","status":"PAUSED"}`',
    '- `METAADS_CREATE_AD_SET` — create an ad set within a campaign',
    '- `METAADS_CREATE_AD` — create an ad within an ad set',
    '- `METAADS_CREATE_AD_CREATIVE` — create ad creative (text, images, links)',
    '- `METAADS_PAUSE_CAMPAIGN` / `METAADS_RESUME_CAMPAIGN` — pause/resume campaigns',
    '- `METAADS_UPDATE_CAMPAIGN` / `METAADS_DELETE_CAMPAIGN` — update/delete campaigns',
    '',
    '**Meta Ads workflow:** Always start with `METAADS_GET_AD_ACCOUNTS` to get the ad account ID, then use that ID for all other operations.',
    '',
    '### LinkedIn',
    '- `LINKEDIN_GET_MY_INFO` — no args needed. Returns user profile',
    '- `LINKEDIN_CREATE_LINKED_IN_POST` — args: `{"text":"..."}`',
    '',
    '### Reddit',
    '- `REDDIT_GET_ME_PREFS` — no args needed. Returns user info',
    '- `REDDIT_SUBMIT_A_LINK_POST` — args: `{"sr":"subreddit","title":"...","url":"..."}`',
    '- `REDDIT_SUBMIT_A_SELF_POST` — args: `{"sr":"subreddit","title":"...","text":"..."}`',
    '- `REDDIT_SEARCH_REDDIT` — args: `{"q":"query"}`',
    '',
    '### Notion',
    '- `NOTION_GET_ABOUT_ME` — no args needed. Returns workspace info',
    '- `NOTION_SEARCH_NOTION_PAGE` — args: `{"search_query":"..."}`',
    '- `NOTION_CREATE_NOTION_PAGE` — create a new page',
    '',
    '### Stripe',
    '- `STRIPE_LIST_PRODUCTS` — args: `{"limit":10}` — list products',
    '- `STRIPE_LIST_ALL_CUSTOMERS` — list customers',
    '- `STRIPE_LIST_ALL_CHARGES` — list payments/charges',
    '',
    '## Important',
    '',
    '- For Google Ads: use `google-bridge.js` (NOT composio-bridge.js)',
    '- For everything else: use `composio-bridge.js`',
    '- Always run `list-apps` on BOTH bridges to see all connected apps',
    '- The bridge output is JSON — parse and present results clearly to the user',
    '- NEVER show raw JSON to the user — summarize the results in a friendly way',
  ].join('\n');
}

module.exports = {
  generateIdentityMd,
  generateUserMd,
  generateBootstrapMd,
  generateBrandMemory,
  generateModelsMd,
  generateComposioMd,
};
